# -*- coding: utf-8 -*-
"""nlp-basics-sol

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G105V9WF3-eHXBfdnvy37zsxQ7EsidQX
"""

import nltk
from nltk.tokenize import WordPunctTokenizer, TreebankWordTokenizer
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, SnowballStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet as wn
import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import string

nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('stopwords')
nltk.download("punkt")
nltk.download('averaged_perceptron_tagger')
nltk.download('tagsets')

"""# **1. Tokenize the description feature**"""

wine = pd.read_csv("/content/winemag-data.csv")

desc = wine['description']

description_tokenized = []
for d in desc:
  description_tokenized.append(nltk.tokenize.word_tokenize(d))

description_tokenized

"""# **2. Remove stop words**"""

stop_words = stopwords.words('english')
punct = ['.', ',', '!', '?', ';', '(', ')', '%']

# Create a capitalized version of stop_words since some of the descriptions
# since some of the descriptions might start with these words
stop_words2 = [string.capwords(s) for s in stop_words]

stop_words.extend(punct)
stop_words.extend(stop_words2)

description_tokenized2 = [[dee for dee in d if dee not in stop_words] for d in description_tokenized]

description_tokenized2

"""# **3. Stem the tokens.**"""

ps = PorterStemmer()

description_tokenized3 = [[ps.stem(dee) for dee in d] for d in description_tokenized2]

description_tokenized3

"""# **4. Lemmatize the tokens**"""

def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wn.ADJ
    elif treebank_tag.startswith('V'):
        return wn.VERB
    elif treebank_tag.startswith('R'):
        return wn.ADV
    else:
        return wn.NOUN

lem = WordNetLemmatizer()

# Lemmatize on description_tokenized2 since lemmatizing and stemming are two separate processes

description_tokenized4 = [[lem.lemmatize(p, pos = get_wordnet_pos(s)) for p, s in nltk.pos_tag(d)] for d in description_tokenized2]

description_tokenized4

"""# **5. Create two new features: "Cleaned_Stem_Description" and "Cleaned_Lemma_Description"**"""

cleaned_stem_desc = pd.Series([" ".join(d) for d in description_tokenized3])

cleaned_lemma_desc = pd.Series([" ".join(d) for d in description_tokenized4])

wine['Cleaned_Stem_Description'] = cleaned_stem_desc
wine['Cleaned_Lemma_Description'] = cleaned_lemma_desc

"""# **6. Build a word cloud based on Cleaned_Lemma_Description**"""

cleaned_lemma_desc2 =" ".join([" ".join(d) for d in description_tokenized4])

cloud = WordCloud().generate(cleaned_lemma_desc2)

plt.imshow(cloud)